services:
  - type: web
    name: naver-blog-bot
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      chmod +x playwright_setup.sh
      ./playwright_setup.sh

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
